# Generated by Django 3.2.5 on 2021-07-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210725_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='client',
            new_name='owner',
        ),
    ]
