# Generated by Django 3.2.5 on 2021-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_auto_20210731_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت پایه و کل بر اساس تعداد خرید'),
        ),
    ]
