# Generated by Django 3.2.5 on 2021-07-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_quoteitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='price',
            new_name='cost',
        ),
    ]
