# Generated by Django 3.2.5 on 2021-07-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_rename_price_quoteitem_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='cost',
            new_name='price',
        ),
    ]
