# Generated by Django 3.2.5 on 2021-07-31 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_rename_price_quoteitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='discount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=0, message="discount can't be negative")], verbose_name='درصد تخفیف'),
        ),
    ]
