# Generated by Django 3.2.5 on 2021-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_alter_quoteitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت خام'),
        ),
    ]
