# Generated by Django 3.2.5 on 2021-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_alter_quoteitem_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='cost',
            new_name='base_cost',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='cost_with_taxation',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت با مالیات'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='final_cost_with_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی با تخفیف'),
        ),
    ]
