# Generated by Django 3.2.5 on 2021-08-02 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0015_auto_20210801_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس ایجاد کننده'),
        ),
    ]
