# Generated by Django 3.2.5 on 2021-08-03 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0034_alter_organization_owner_email'),
        ('marketing', '0017_alter_quoteitem_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowUp',
            new_name='QuoteFollowUp',
        ),
    ]
