# Generated by Django 3.2.5 on 2021-08-03 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0018_rename_followup_quotefollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email_address', models.EmailField(max_length=254, verbose_name='ایمیل گیرنده')),
                ('was_successfull', models.BooleanField(default=False, verbose_name='ایمیل ارسال شد؟')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال شده')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارسال کننده')),
            ],
        ),
    ]
