# Generated by Django 3.2.5 on 2021-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_quoteemailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت خام محصول'),
        ),
    ]
