# Generated by Django 3.2.5 on 2021-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_quoteitem_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='final_cost_with_discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت نهایی با تخفیف'),
        ),
    ]
