# Generated by Django 3.2.5 on 2021-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_alter_quoteitem_final_cost_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='base_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت خام'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='cost_with_taxation',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت با مالیات'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1, verbose_name='تعداد خرید'),
        ),
    ]
