# Generated by Django 3.2.5 on 2021-07-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_catalog',
            field=models.ImageField(blank=True, upload_to='media/catalogs/pictures', verbose_name='عکس کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf_catalog',
            field=models.FileField(blank=True, upload_to='media/catalogs/pdfs', verbose_name='پی دی اف کاتالوگ'),
        ),
    ]
