# Generated by Django 3.2.5 on 2021-07-21 16:32

from django.db import migrations
import inventory.fields

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_catalog',
            field=inventory.fields.PdfField(blank=True, upload_to='media/catalogs/pdfs', verbose_name='پی دی اف کاتالوگ'),
        ),
    ]
