# Generated by Django 3.2.5 on 2021-07-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210724_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproduct',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام محصول'),
        ),
    ]
