# Generated by Django 3.2.5 on 2021-07-21 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=50, verbose_name='نام استان')),
                ('organization_name', models.CharField(max_length=50, verbose_name='نام سازمان')),
                ('organization_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='شماره تلفن سازمان')),
                ('workers_number', models.PositiveIntegerField(default=1, verbose_name='تعداد کارگران')),
                ('expert_full_name', models.CharField(max_length=50, verbose_name='نام خانوادگی مخاطب')),
                ('expert_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='شماره تلفن مخاطب')),
                ('expert_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایحاد کننده')),
                ('manufacturedـproducts', models.ManyToManyField(to='organization.OrganizationProduct', verbose_name='محصول تولیدی')),
            ],
        ),
    ]
