# Generated by Django 3.2.5 on 2021-07-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_manufacturedـproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='expert_email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='expert_full_name',
            new_name='client_full_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='expert_phone_number',
            new_name='client_phone_number',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='creator',
            new_name='expert_creator',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='workers_number',
            new_name='workers_size',
        ),
    ]
