# Generated by Django 3.2.5 on 2021-07-24 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210724_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='client_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='شماره تلفن مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='شماره تلفن سازمان'),
        ),
    ]
