# Generated by Django 3.2.5 on 2021-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مخاطب'),
        ),
    ]
