# Generated by Django 3.2.5 on 2021-07-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_expert_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='client_email',
            new_name='owner_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='client_full_name',
            new_name='owner_full_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='client_phone_number',
            new_name='owner_phone_number',
        ),
    ]
