# Generated by Django 3.2.5 on 2021-07-25 13:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_auto_20210725_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='expert_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل کارفرما'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_full_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی کارفرما'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='شماره تلفن کارفرما'),
        ),
    ]
