# Generated by Django 3.2.5 on 2021-07-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20210725_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_full_name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی کارفرما'),
        ),
    ]
