# Generated by Django 3.2.5 on 2021-07-26 11:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_organization_expert_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده'),
        ),
    ]
