# Generated by Django 3.2.5 on 2021-07-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_organization_created_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('organization_phone_number',)},
        ),
    ]
