# Generated by Django 3.2.5 on 2021-07-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('organization_phone_number', 'owner_phone_number')},
        ),
    ]
