# Generated by Django 3.2.5 on 2021-07-26 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='شماره تلفن سازمان'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='شماره تلفن کارفرما'),
        ),
    ]
