# Generated by Django 3.2.5 on 2021-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20210726_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
    ]
