# Generated by Django 3.2.5 on 2021-07-26 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^((?:\\+98|0)(\\d){2}(\\d){8})$')], verbose_name='شماره تلفن سازمان'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^((?:\\+98|0)(\\d){2}(\\d){8})$')], verbose_name='شماره تلفن کارفرما'),
        ),
    ]
