# Generated by Django 3.2.5 on 2021-07-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20210726_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مخاطب'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی مخاطب'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner_second_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پسوند مخاطب'),
        ),
    ]
