# Generated by Django 3.2.5 on 2021-07-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20210728_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='نام مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='نام خانوادگی مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_second_last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='پسوند مخاطب'),
        ),
    ]
