# Generated by Django 3.2.5 on 2021-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_auto_20210728_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_second_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پسوند مخاطب'),
        ),
    ]
