# Generated by Django 3.2.5 on 2021-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20210728_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='نام مخاطب'),
        ),
    ]
