# Generated by Django 3.2.5 on 2021-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_alter_organization_owner_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='نام خانوادگی مخاطب'),
        ),
    ]
