# Generated by Django 3.2.5 on 2021-07-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_alter_organization_owner_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_second_last_name',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='پسوند مخاطب'),
        ),
    ]
