# Generated by Django 3.2.5 on 2021-07-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_alter_organization_owner_second_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner_full_name',
        ),
    ]
