# Generated by Django 3.2.5 on 2021-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_remove_organization_owner_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام سازمان'),
        ),
    ]
