# Generated by Django 3.2.5 on 2021-07-28 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_alter_organization_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner_phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is invalid', regex='^((?:\\+98|0)(\\d){2}(\\d){8})$')], verbose_name='شماره تلفن مخاطب'),
        ),
    ]
