# Generated by Django 3.2.5 on 2021-07-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_auto_20210728_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='organization.province', verbose_name='نام استان'),
        ),
    ]
