# Generated by Django 3.2.5 on 2021-07-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_alter_organization_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='province_name',
        ),
    ]
