# Generated by Django 3.2.5 on 2021-07-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_alter_province_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل مخاطب'),
        ),
    ]
